"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.initializeApp = exports.getDatabase = exports.onValue = exports.update = exports.remove = exports.push = exports.get = exports.set = exports.ref = exports.db = exports.DB = void 0;
exports.DB = null;
exports.db = null;
const ref = () => null;
exports.ref = ref;
const set = () => Promise.resolve();
exports.set = set;
const get = () => Promise.resolve({ val: () => null, exists: () => false });
exports.get = get;
const push = () => Promise.resolve({ key: 'mock-key' });
exports.push = push;
const remove = () => Promise.resolve();
exports.remove = remove;
const update = () => Promise.resolve();
exports.update = update;
const onValue = (_ref, cb) => { cb({ val: () => null, exists: () => false }); return () => { }; };
exports.onValue = onValue;
const getDatabase = () => null;
exports.getDatabase = getDatabase;
const initializeApp = () => ({});
exports.initializeApp = initializeApp;
